cache:
  mount:
    - wheeldir

clone:
  skip_verify: true

build:
  image: python:3.5.1-alpine
  commands:
    - apk add --update g++ make
    - pip install --upgrade pip setuptools wheel
    - pip wheel -r requirements.txt --wheel-dir=wheeldir --find-links=wheeldir
    - pip install -r requirements.txt --use-wheel --no-index --find-links=wheeldir
    - py.test --cov=starwatts --cov-report term --cov-report html
    - mv htmlcov/ docs/_build/html/
    - /usr/local/bin/sphinx-build -b html -d docs/_build/doctrees docs docs/_build/html
  environment:
    - ACCESS_KEY=$$ACCESS_KEY
    - PRIVATE_KEY=$$PRIVATE_KEY
